name: Testing Simple Todo App
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, redis, pdo_pgsql
          coverage: pcov
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          composer run-script post-install-cmd --no-interaction
          php database/migrate.php
      # Add a step to run migrations if required
      - name: Test with phpunit
        run: vendor/bin/phpunit
